name: Reusable w/ Concurrency

on:
  workflow_call:
    inputs:
      flag:
        type: string
        required: true
  
jobs:
  yes-concurrency:
    if: ${{ inputs.flag == 'true' }}
    concurrency:
      group: ${{ github.event.repository.name }}-deploy-dev
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
      
  no-concurrency:
    if: ${{ inputs.flag != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
      
